### ISSUE TITLE
пришел душнила

### ISSUE THREAD

**Issue by Badsnus** [I-ToSa-I/AsyncPayments#1]
1)pycache убери
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/712aaad3-a456-4826-869f-bcdc46f229ea)
2)По пепке надо импорты по афлвиту + не оч хорошо относительные импорты хуярить
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/1eb8bff8-0911-4e9d-b3d7-477bf0839dac)
3)Почему ты где-то пишешь тайпхинты, а где-то нет
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/02f827a1-87f4-42e0-9f79-a7ded4db8d79)
4)А если дропнет ошибку? почему ты эт не отлавливаешь?
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/be9f8148-caa0-4734-8910-3b5ecac3897f)
5) https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/9bd107cf-e795-4bf4-a803-1766e4fc11f0)
6)Какая-то очень странная логика, почему у тебя метод _checkexception ваще возвращать response должен? Лучше уж сделать так чтобы ты его прост вызывал и он проверял все, а уже после этого ты из своей функции return response делал
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/a619232e-b5a6-4575-ad12-630e70761a9b)
7)Тут ваще проблема c import order + никогда не делай import *
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/e622a07c-ae28-49ff-9aa0-073990caa8ae)
8)По пепке тут должна быть запятая
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/c1b5ec22-03ea-4739-96b7-9fcf1da9e688)
9)В питоне >=3.10  эт можно и без модуля тайпинг делать - почитай про эт
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/7e3a4e43-1723-46ec-9f99-9b46a2fc0d91)
10) У тебя во всех классах такая шняга - чисто DRY идет нахуй, очев эт куда-то вынести надо
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/24c45a6d-673b-4129-b817-e281387b5499)
11) У словаря есть метод pop() - лучше юзать его, а не del
https://github.com/I-ToSa-I/AsyncPayments/blob/3fbaaf3f4a552b65ae25e4584a7cf58780a1cd16/AsyncPayments/aaio/api.py#L77
12)Очевидно, что эту логику надо выносить в отдельный метод (там всякие SRP и прочее) )
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/d17a2256-6f36-49b6-b4e1-aae784e9772e)
13)У тебя вот опять - куча логики повторяется, эт ваще фиксить надо везде
14)А почему если их несколько, то ты тупо ретурнишь список словарей (ну на скок я понял)? Почему все элементы списка в твой врапер не обернуть?
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/cd1816a5-af93-486c-bf9d-e91c4e019e51)
15) А на кой черт нужны такие комменты? Они не несут никакой пользы прост занимают место)
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/ad045547-4ed7-4c8f-9f03-7f607cc965ce)
16) Отступы у тебя ваще каким-то рандомным методом генерятся. Где то 3 строки, где-то одна между классами. Надо по pep8 сделать
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/1741354f-1cf6-4348-9ec3-888d91608bac)
17)Ты вот эт опять же пишешь почти в каждом месте, почему это не вынести куда-нибудь? Ну и передавать POST строкой чет сомнительная штука, потому что одна опечатка и все сломалось
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/f3d2c5a1-6a2c-4495-9522-3fc0d71d5a4a)
18)Почему ты кста response такскаешь в словарях, почему не в датаклассы его обернуть? 
![image](https://github.com/I-ToSa-I/AsyncPayments/assets/91815912/623bfc61-b79a-4cd6-81cc-43f8f8252e6f)

**Comment by Badsnus** [comment]
ну еще бы не помешало написать юнит тесты

**Comment by reasontodie** [comment]
сходи нахуй, душнила

**Comment by Badsnus** [comment]
> сходи нахуй, душнила

злой ты какой-то(

**Comment by reques6e** [comment]
Я пока читал, инсульт получил.

**Comment by I-ToSa-I** [comment]
Thanks!
