### ISSUE TITLE
AsyncLolzteamMarketPayment mistake

### ISSUE THREAD

**Issue by Sergey-sply** [I-ToSa-I/AsyncPayments#2]
`class AsyncLolzteamMarketPayment(RequestsClient):
    API_HOST: str = "https://lzt.market"

    def __init__(self, token: str, user_id: int, user_nickname: str) -> None:
        """
        Initialize LolzteamMarket API client
        :param token: Your Lolzteam Token
        :param user_id: Your Lolzteam User ID
        :param user_nickname: Your Lolzteam User nickname
        """
        super().__init__()
        self.__token = token
        self.__user_id = user_id
        self.__nickname = user_nickname
        self.__headers = {
            'Authorization': f'Bearer {self.__token}',
            "Accept": "application/json"
        }
        self.__base_url = "https://api.lzt.market"
        self.__get_method = "GET"
        self.__payment_name = "crystalPay"
        self.check_values()`
        
        Ошибка в строке `self.__payment_name = "crystalPay"`, там вроде как "lolz" должно быть

**Comment by I-ToSa-I** [comment]
исправлено, спасибо
